fft_script : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/fft_path.R'
wps_script : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/extractReadStartsFromBAM_Region_WPS.py'
concatfft : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/concat_fft.py'
concatwps : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/concat_wps.py'
cfdna_analyse_script : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/cfdna_analyse.py'
figure_script : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/utility/figure.py'
summary_script : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/utility/utility/summary.py'
scdata_path : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/database/single_cell.expression.csv'
bed_file : '/mnt/dfc_data2/project/linyusen/project/cfdna_r_github/database/hg38.tss.10000.bed'
rscript_software : '/mnt/dfc_data1/home/linyusen/miniconda3/envs/cfdna/bin/Rscript'
python27_software : '/mnt/dfc_data1/home/linyusen/miniconda3/envs/cfdna/bin/python'
python38_software : '/mnt/dfc_data1/home/linyusen/miniconda3/envs/lys/bin/python'